### ISSUE TITLE
Windows `Cannot run program "git": CreateProcess error=2, The system cannot find the file specified`

### ISSUE THREAD

**Issue by jredfox** [anatawa12/ForgeGradle-2.3#102]
do not run git commands unless you plan to manually install them for the user
```

C:\Users\jredfox\Documents\dev\MDK>gradlew setupdecompworkspace eclipse
Downloading https://services.gradle.org/distributions/gradle-6.3-all.zip
.............10%..............20%..............30%..............40%..............50%..............60%.............70%..............80%..............90%..............100%

Welcome to Gradle 6.3!

Here are the highlights of this release:
 - Java 14 support
 - Improved error messages for unexpected failures

For more details see https://docs.gradle.org/6.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\jredfox\Documents\dev\MDK\build.gradle.kts' line: 440

* What went wrong:
Cannot run program "git": CreateProcess error=2, The system cannot find the file specified
> CreateProcess error=2, The system cannot find the file specified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 43s

C:\Users\jredfox\Documents\dev\MDK>
```

**Comment by anatawa12** [comment]
It looks you're trying to create mod but downloading this repository is not the correct way. 
This repository contains ForgeGradle, an Gradle plugin used by MDK and this is not MDK. 
You should download MDK and replace with this ForgeGradle.

https://github.com/anatawa12/ForgeGradle-2.3?tab=readme-ov-file#how-to-use-this-forgegradle-instead-of-official-forgegradle

**Comment by jredfox** [comment]
@anatawa12 that didn't really work either the only thing that works with eclipse is to download an older 1.12.2 MDK fallow the instructions
* `winget install --id Git.Git -e --source winget`
* replace everything above the version in the build.gradle with this
```
buildscript {
    repositories {
        jcenter()
    mavenCentral()
        maven { url = "https://files.minecraftforge.net/maven" }
    }
    dependencies {
        classpath("com.anatawa12.forge:ForgeGradle:2.3-1.0.+") {
            changing = true
        }
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'
//Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.
```
* gradle/wrapper/gradle-wrapper.properties replace distributionUrl with this
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.4.1-bin.zip`
* run gradlew setupdecompworkspace
* run gradlew setupdecompworkspace eclipse

the instructions were confusing, unclear and completely missing the fact you have to have installed git which not most people want to do.

**Comment by anatawa12** [comment]
The git is not required to run mdk.

**Comment by anatawa12** [comment]
The git is not required to run mdk (projects with forgegradle).

> download an older 1.12.2 MDK fallow the instructions

it's is precondition.
the document is for people already have some mod developing,.
the README descrives how to replace, there is no document to create new mod yet.

**Comment by anatawa12** [comment]
I have added [How to create project with this ForgeGradle instead of official ForgeGradle](https://github.com/anatawa12/ForgeGradle-2.3/blob/FG_2.3/README.md#how-to-create-project-with-this-forgegradle-instead-of-official-forgegradle) to README

**Comment by jredfox** [comment]
@anatawa12 1.12.2 did not require git to use forge gradle. and I am confused on why you keep saying use ForgeGradle instead of ForgeGradle? you Mean anatawa12ForgeGradle?

however when I run the projects with your fixes it requires git so I am saying you need to download it for the user if it's not found in the path and set it to their enviorment path for the user so no admin is required or require admin and run the powershell command for them (windows)

**Comment by anatawa12** [comment]
> 1.12.2 did not require git to use forge gradle.

Yes. and not require git to use this ForgeGradle.

> I am confused on why you keep saying use ForgeGradle instead of ForgeGradle? you Mean anatawa12ForgeGradle?

I'm always saying "to use this (fork of) ForgeGradle instead of official ForgeGradle".
Since both project is ForgeGradle, I'm distinguishing two with "official" and "this/my (fork of)".

> however when I run the projects with your fixes it requires git

Could you show me the error message?
[The error message above](https://github.com/anatawa12/ForgeGradle-2.3/issues/102#issue-2279292614) looks mentioning the `build.gradle.kts` in this repository.
It is not necessary to build this repository for developing your mod.

https://github.com/anatawa12/ForgeGradle-2.3/blob/837fb50e5d1e5f13c28fa773deee7ed3620ae106/build.gradle.kts#L440

**Comment by jredfox** [comment]
Unable to reproduce with Modifying only Forge's MDK with your plugin

Please fix the unclear readme on how to use this fix. Say Usage Download Forge MDK from their website then modify them with x and y. Also you edited the URL inside of the **build.gradle** yet you didn't put it in your instructions. it's just confusing to me. The average coder even would assume this project that has releases is the actual replacement for Forge MDK and download this instead.
