### ISSUE TITLE
Build failures due to recent Forge migration

### ISSUE THREAD

**Issue by tomdodd4598** [anatawa12/ForgeGradle-2.3#31]
Hey there. I found this project after looking for solutions to the recent issues using FG 2.3 due to [Forge's recent migration](https://twitter.com/ForgeDevTeam/status/1384341469687730188). I think it could be that some of the hardcoded URL strings just need updating from `files.minecraftforge.net/maven` to `maven.minecraftforge.net`.

~~Additionally, while attempting to run `gradlew` while using `"com.anatawa12.forge:ForgeGradle:2.3-1.0.4"` or `"com.anatawa12.forge:ForgeGradle:2.3-1.0.2"`, I am getting another error:~~
~~`> org.gradle.api.internal.TaskOutputsInternal.dir(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskOutputFilePropertyBuilder;`~~

~~Finally, while attempting to run `gradlew` while using `"com.anatawa12.forge:ForgeGradle:2.3-1.0.1"` or `"com.anatawa12.forge:ForgeGradle:2.3-1.0.3"`, I am getting a different error:~~
~~`> Failed to apply plugin [id 'net.minecraftforge.gradle.forge']`~~
~~`> Configuration with name 'implementation' not found.`~~

**Comment by anatawa12** [comment]
Which version of Gradle are you using to get `org.gradle.api.internal.TaskOutputsInternal.dir(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskOutputFilePropertyBuilder;`?

**Comment by tomdodd4598** [comment]
Sorry, that was my bad, forget the second and third issues, I was using a fresh MDK and that comes with gradle 2, updated to gradle 4 and they disappeared.

**Comment by anatawa12** [comment]
@turbodiesel4598 Which version of forge is your target? If you're targeting 1.12.2, you can use ForgeGradle 4.1.x with forge 2855. If you can use ForgeGradle 4.1.x, I'll close this repository.

**Comment by tomdodd4598** [comment]
I wasn’t able to get either FG 3 or FG 4 to work, though it’s very possible that I made a mistake. In the meantime I’ve moved to using another fork of FG 2.3 with the updated URL, and things seem to be working again.
