### ISSUE TITLE
Can I make this project sunset?

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/ForgeGradle-2.3#33]
This project is only used for 1.12.2 development but 1.12.2 can be developed with forgegradle 3.x/4.x.

Because of MinecraftForge/ForgeGradle#769, It was hard but now it's fixed so it's not too hard for the most developers I think.

## Step to use fixed versions of ForgeGradle 4.x
1. remove those cache files if exitsts
   `~/.gradle/caches/forge_gradle/mcp_repo/net/minecraft/client/1.12.2/client-1.12.2.pom`
   `~/.gradle/caches/forge_gradle/minecraft_repo/versions/1.12.2/client-1.12.2.pom`
2. modify build.gradle like [anatawa12/migrating-ForgeGradle-3.2-to-4.x](https://github.com/anatawa12/migrating-ForgeGradle-3.2-to-4.x/compare/mdk..master) (you can see steps by seeing commits.)
3. now it should be working!

**Comment by anatawa12** [comment]
Nierot/minecraft-kotlin-mod-test#1, shs3182ym/twitch-chat-minecraft-overlay#1 and snsvim/pma-mc#1 are no response, So I think they're inactive. I'll ignore those repositories.

**Comment by ApeaSuperz** [comment]
You fucking life saver

**Comment by LordDarthDan** [comment]
I'd say no, I'm currently trying to build a mod referencing ForgeGradle2.3 and I'm so glad this exists.

**Comment by anatawa12** [comment]
I've changed my mind to keep this fork as maintenance mode instead of sunset this project.
I'll fix fatal bugs but I'll not add features including newer Gradle Support (unless I have enough free time & motivation).
Even in the maintenance mode, feature PullRequest are welcome!
If you want some features including newer Gradle support, please make PullRequest!
I'll merge such a PullRequest, and release newer release of FrogeGradle 2.3-1.x.y.
