### ISSUE TITLE
Plugin disabled by forge people few days ago

### ISSUE THREAD

**Issue by BSarmady** [anatawa12/ForgeGradle-2.3#34]
Forge guys deleted the following file from their maven, effectively disabling your plugin.

https://files.minecraftforge.net/maven/de/oceanlabs/mcp/versions.json 

I find it irony that every time I want to compile my minecraft mods, I have to downgrade java (environment settings, path ... ), then downgrade gradle too (environment, path), then rely on resources (libraries, simple information) hosted by someone else which I don't even know if they will be there in a year later.

You can see their usual behavior in this forum post, (not supported, closing the thread)
https://forums.minecraftforge.net/topic/100004-451252

Since their plugin doesn't work with gradle 6.x.x, your plugin becomes the only choice to compile minecraft mods. with this file deleted I cannot even verify the behavior of the mod and fix bugs on 

I guess to avoid such time bombs, there should be an option to use files from local folder without needing to refer to an online source. same goes for dependencies and repositories that you are adding to project during runtime.

Thanks in advance

**Comment by anatawa12** [comment]
@bobsort Is there any reason to use this plugin? Could you use ForgeGradle 4.x?

**Comment by BSarmady** [comment]
yes, Since their plugin doesn't work with gradle 6.x.x, After looking up for 3 complaint message from plugin that this thing is not set and that thing is not compatible, I gave up.

another reason is I couldn't build their gradle plugin source code either, on the other hand for some reason, your plugin compile and build on first try without issue.

Also as for issue, they put back the file again and build is working again. However to avoid such incidents, I still suggest adding a property to Minecraft buildscript tag to allow setting offline folder (maven) instead of the online locations. this way you are not distributing Minecraft code and resources but people who have access to these resources, can download and put them in right directory (including MCP which will go offline in few months as I heard)

**Comment by anatawa12** [comment]
OKey, I'll continue supporting FG2.3. Please wait for few days until release.

**Comment by anatawa12** [comment]
@bobsort must be fixed in 1.0.5. Please try it.

**Comment by BSarmady** [comment]
Thank you, I will try it in a while. While at it, would it be possible to fix dependency usage too. currently plugin doesn't seem to be honoring buildscript dependencies and reading its dependencies directly from files.minecraftforge.net and maven (is it inserting repositories at start of dependencies?) 

my build script starts like this, which I'm expecting it to read dependencies from my local maven but I see gradle still downloading them from web again (I already have them all in my local maven and it is about 200Mb).

```
buildscript {
    repositories {
        maven { url = "G:/maven1" }
        maven { url = "G:/maven" }
        //jcenter()
        mavenCentral()
        maven { name = 'Forge'; url = 'https://files.minecraftforge.net/maven' }
    }
    dependencies {
        classpath("com.anatawa12.forge:ForgeGradle:2.3-1.0.4") { changing = true }
    }
}

```

**Comment by anatawa12** [comment]
Most dependencies for compile time or runtime will be downloaded with top-level configurations, not inside buildscript.
If you have userdev in `file:///G:/maven1`, please add `file:///G:/maven1` to top-level repositories like this below:

```
repositories {
    maven { url = "G:/maven1" }
}
```

Some files like `/de/oceanlabs/mcp/versions.json` will be always downloaded from `https://maven.minecraftforge.net` because it's hardcoded in static context.

**Comment by BSarmady** [comment]
From my understanding (correct me if I'm wrong), repositories in buildscript are locations of build dependencies such as "kotlin-stdlib-1.4.0", "gradle-ext-profiler-tooling" or where to find "com.anatawa12.forge:ForgeGradle"


repositories in root of buildscript are dependencies of project itself, am I right?

**Comment by anatawa12** [comment]
@bobsort I'm sorry long time no repsponse. I didn't noticed that replay.

Repositories in buildscript is not dependencies of project itself, dependencies of `build.gradle`
