### ISSUE TITLE
Can I use forgegradle 2.3 in 1.10.2?

### ISSUE THREAD

**Issue by LoboMetalurgico** [anatawa12/ForgeGradle-2.3#48]
I'm developing a multi-version mod, and I found your repositories wich support latest gradle version, but the minecraft 1.10.2 uses ForgeGradle 2.2 and I want to know if will run using your 2.3 version.

**Comment by anatawa12** [comment]
I don't know. Please try yourself. If you have questions to try this instead of FG 2.2, you are welcome to ask me.

**Comment by LoboMetalurgico** [comment]
Unfortunately I couldn't run it. The compiler throw an error that version 1.12.2 was the minimum version for this gradle forge. Anyway, thanks for the fast response.
